from . import education_student
from . import education_classroom
from . import education_major
from . import education_major_curriculum
from . import education_schedule
from . import education_student_achievement
from . import res_partner
from . import education_subject
from . import education_subject_detail
from . import education_student_attendance